namespace EmuDotNet.Core.MOS6502;

public enum Instruction
{
    ADC, AND, ASL, BCC, BCS, BEQ, BIT, BMI,
    BNE, BPL, BRK, BVC, BVS, CLC, CLD, CLI,
    CLV, CMP, CPX, CPY, DEC, DEX, DEY, EOR,
    INC, INX, INY, JMP, JSR, LDA, LDX, LDY,
    LSR, NOP, ORA, PHA, PHP, PLA, PLP, ROL,
    ROR, RTI, RTS, SBC, SEC, SED, SEI, STA,
    STX, STY, TAX, TAY, TSX, TXA, TXS, TYA,
    UNK // Unknown
}

public enum AddressMode
{
    ABS, ABX, ABY, IMM, IMP, IND,
    INX, INY, REL, ZPG, ZPX, ZPY,
    UNK // Unknown
}

public record Opcode(Instruction Instruction, AddressMode AddressMode)
{
    public static Opcode Unknown => new(Instruction.UNK, AddressMode.UNK);
}

public static class OpcodeParser
{
    public static Opcode Parse(byte value) => value switch
    {
        0x00 => new(Instruction.BRK, AddressMode.IMP),
        0x01 => new(Instruction.ORA, AddressMode.INX),
        0x05 => new(Instruction.ORA, AddressMode.ZPG),
        0x06 => new(Instruction.ASL, AddressMode.ZPG),
        0x08 => new(Instruction.PHP, AddressMode.IMP),
        0x09 => new(Instruction.ORA, AddressMode.IMM),
        0x0A => new(Instruction.ASL, AddressMode.IMP),
        0x0D => new(Instruction.ORA, AddressMode.ABS),
        0x0E => new(Instruction.ASL, AddressMode.ABS),
        0x10 => new(Instruction.BPL, AddressMode.REL),
        0x11 => new(Instruction.ORA, AddressMode.INY),
        0x15 => new(Instruction.ORA, AddressMode.ZPX),
        0x16 => new(Instruction.ASL, AddressMode.ZPX),
        0x18 => new(Instruction.CLC, AddressMode.IMP),
        0x19 => new(Instruction.ORA, AddressMode.ABY),
        0x1D => new(Instruction.ORA, AddressMode.ABX),
        0x1E => new(Instruction.ASL, AddressMode.ABX),
        0x20 => new(Instruction.JSR, AddressMode.ABS),
        0x21 => new(Instruction.AND, AddressMode.INX),
        0x24 => new(Instruction.BIT, AddressMode.ZPG),
        0x25 => new(Instruction.AND, AddressMode.ZPG),
        0x26 => new(Instruction.ROL, AddressMode.ZPG),
        0x28 => new(Instruction.PLP, AddressMode.IMP),
        0x29 => new(Instruction.AND, AddressMode.IMM),
        0x2A => new(Instruction.ROL, AddressMode.IMP),
        0x2C => new(Instruction.BIT, AddressMode.ABS),
        0x2D => new(Instruction.AND, AddressMode.ABS),
        0x2E => new(Instruction.ROL, AddressMode.ABS),
        0x30 => new(Instruction.BMI, AddressMode.REL),
        0x31 => new(Instruction.AND, AddressMode.INX),
        0x35 => new(Instruction.AND, AddressMode.ZPX),
        0x36 => new(Instruction.ROL, AddressMode.ZPX),
        0x38 => new(Instruction.SEC, AddressMode.IMP),
        0x40 => new(Instruction.RTI, AddressMode.IMP),
        0x41 => new(Instruction.EOR, AddressMode.INX),
        0x45 => new(Instruction.EOR, AddressMode.ZPG),
        0x46 => new(Instruction.LSR, AddressMode.ZPG),
        0x48 => new(Instruction.PHA, AddressMode.IMP),
        0x49 => new(Instruction.EOR, AddressMode.IMM),
        0x4A => new(Instruction.LSR, AddressMode.IMP),
        0x4C => new(Instruction.JMP, AddressMode.ABS),
        0x4D => new(Instruction.EOR, AddressMode.ABS),
        0x4E => new(Instruction.LSR, AddressMode.ABS),
        0x50 => new(Instruction.BVC, AddressMode.REL),
        0x51 => new(Instruction.EOR, AddressMode.INY),
        0x55 => new(Instruction.EOR, AddressMode.ZPX),
        0x56 => new(Instruction.LSR, AddressMode.ZPX),
        0x58 => new(Instruction.CLI, AddressMode.IMP),
        0x59 => new(Instruction.EOR, AddressMode.ABY),
        0x5D => new(Instruction.EOR, AddressMode.ABX),
        0x5E => new(Instruction.LSR, AddressMode.ABX),
        0x60 => new(Instruction.RTS, AddressMode.IMP),
        0x61 => new(Instruction.ADC, AddressMode.INX),
        0x65 => new(Instruction.ADC, AddressMode.ZPG),
        0x66 => new(Instruction.ROR, AddressMode.ZPG),
        0x68 => new(Instruction.PLA, AddressMode.IMP),
        0x69 => new(Instruction.ADC, AddressMode.IMM),
        0x6A => new(Instruction.ROR, AddressMode.IMP),
        0x6C => new(Instruction.JMP, AddressMode.IND),
        0x6D => new(Instruction.ADC, AddressMode.ABS),
        0x6E => new(Instruction.ROR, AddressMode.ABS),
        0x70 => new(Instruction.BVS, AddressMode.REL),
        0x71 => new(Instruction.ADC, AddressMode.INY),
        0x75 => new(Instruction.ADC, AddressMode.ZPX),
        0x76 => new(Instruction.ROR, AddressMode.ZPX),
        0x78 => new(Instruction.SEI, AddressMode.IMP),
        0x79 => new(Instruction.ADC, AddressMode.ABY),
        0x7D => new(Instruction.ADC, AddressMode.ABX),
        0x7E => new(Instruction.ROR, AddressMode.ABX),
        0x81 => new(Instruction.STA, AddressMode.INX),
        0x84 => new(Instruction.STY, AddressMode.ZPG),
        0x85 => new(Instruction.STA, AddressMode.ZPG),
        0x86 => new(Instruction.STX, AddressMode.ZPG),
        0x88 => new(Instruction.DEY, AddressMode.IMP),
        0x8A => new(Instruction.TXA, AddressMode.IMP),
        0x8C => new(Instruction.STY, AddressMode.ABS),
        0x8D => new(Instruction.STA, AddressMode.ABS),
        0x8E => new(Instruction.STX, AddressMode.ABS),
        0x90 => new(Instruction.BCC, AddressMode.REL),
        0x91 => new(Instruction.STA, AddressMode.INY),
        0x94 => new(Instruction.STY, AddressMode.ZPX),
        0x95 => new(Instruction.STA, AddressMode.ZPX),
        0x96 => new(Instruction.STX, AddressMode.ZPY),
        0x98 => new(Instruction.TYA, AddressMode.IMP),
        0x99 => new(Instruction.STA, AddressMode.ABY),
        0x9A => new(Instruction.TXS, AddressMode.IMP),
        0x9D => new(Instruction.STA, AddressMode.ABX),
        0xA0 => new(Instruction.LDY, AddressMode.IMM),
        0xA1 => new(Instruction.LDA, AddressMode.INX),
        0xA2 => new(Instruction.LDX, AddressMode.IMM),
        0xA4 => new(Instruction.LDY, AddressMode.ZPG),
        0xA5 => new(Instruction.LDA, AddressMode.ZPG),
        0xA6 => new(Instruction.LDX, AddressMode.ZPG),
        0xA8 => new(Instruction.TAY, AddressMode.IMP),
        0xA9 => new(Instruction.LDA, AddressMode.IMM),
        0xAA => new(Instruction.TAX, AddressMode.IMP),
        0xAC => new(Instruction.LDY, AddressMode.ABS),
        0xAD => new(Instruction.LDA, AddressMode.ABS),
        0xAE => new(Instruction.LDX, AddressMode.ABS),
        0xB0 => new(Instruction.BCS, AddressMode.REL),
        0xB1 => new(Instruction.LDA, AddressMode.INY),
        0xB4 => new(Instruction.LDY, AddressMode.ZPX),
        0xB5 => new(Instruction.LDA, AddressMode.ZPX),
        0xB6 => new(Instruction.LDX, AddressMode.ZPY),
        0xB8 => new(Instruction.CLV, AddressMode.IMP),
        0xB9 => new(Instruction.LDA, AddressMode.ABY),
        0xBA => new(Instruction.TSX, AddressMode.IMP),
        0xBC => new(Instruction.LDY, AddressMode.ABX),
        0xBD => new(Instruction.LDA, AddressMode.ABX),
        0xBE => new(Instruction.LDX, AddressMode.ABY),
        0xC0 => new(Instruction.CPY, AddressMode.IMM),
        0xC1 => new(Instruction.CMP, AddressMode.INX),
        0xC4 => new(Instruction.CPY, AddressMode.ZPG),
        0xC5 => new(Instruction.CMP, AddressMode.ZPG),
        0xC6 => new(Instruction.DEC, AddressMode.ZPG),
        0xC8 => new(Instruction.INY, AddressMode.IMP),
        0xC9 => new(Instruction.CMP, AddressMode.IMM),
        0xCA => new(Instruction.DEX, AddressMode.IMP),
        0xCC => new(Instruction.CPY, AddressMode.ABS),
        0xCD => new(Instruction.CMP, AddressMode.ABS),
        0xCE => new(Instruction.DEC, AddressMode.ABS),
        0xD0 => new(Instruction.BNE, AddressMode.REL),
        0xD1 => new(Instruction.CMP, AddressMode.INY),
        0xD5 => new(Instruction.CMP, AddressMode.ZPX),
        0xD6 => new(Instruction.DEC, AddressMode.ZPX),
        0xD8 => new(Instruction.CLD, AddressMode.IMP),
        0xD9 => new(Instruction.CMP, AddressMode.ABY),
        0xDD => new(Instruction.CMP, AddressMode.ABX),
        0xDE => new(Instruction.DEC, AddressMode.ABX),
        0xE0 => new(Instruction.CPX, AddressMode.IMM),
        0xE1 => new(Instruction.SBC, AddressMode.INX),
        0xE4 => new(Instruction.CPX, AddressMode.ZPG),
        0xE5 => new(Instruction.SBC, AddressMode.ZPG),
        0xE6 => new(Instruction.INC, AddressMode.ZPG),
        0xE8 => new(Instruction.INX, AddressMode.IMP),
        0xE9 => new(Instruction.SBC, AddressMode.IMM),
        0xEA => new(Instruction.NOP, AddressMode.IMP),
        0xEC => new(Instruction.CPX, AddressMode.ABS),
        0xED => new(Instruction.SBC, AddressMode.ABS),
        0xEE => new(Instruction.INC, AddressMode.ABS),
        0xF0 => new(Instruction.BEQ, AddressMode.REL),
        0xF1 => new(Instruction.SBC, AddressMode.INY),
        0xF5 => new(Instruction.SBC, AddressMode.ZPX),
        0xF6 => new(Instruction.INC, AddressMode.ZPX),
        0xF8 => new(Instruction.SED, AddressMode.IMP),
        0xF9 => new(Instruction.SBC, AddressMode.ABY),
        0xFD => new(Instruction.SBC, AddressMode.ABX),
        0xFE => new(Instruction.INC, AddressMode.ABX),
        _ => new(Instruction.UNK, AddressMode.UNK)
    };
}